version: '3.8'

services:
  wordpress:
    container_name: wordpress_docker
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/html/
    env_file:
      - .env
    environment:
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    init: true
    networks:
      - inception 
    depends_on:
      mariadb:
        condition : service_healthy
    restart: unless-stopped

  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx_docker
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - DOMAIN_NAME=abravo.42.fr
      - CERTS=/etc/ssl/certs/inception.ctr
      - CERTS_KEY=/etc/ssl/private/inception.key
    restart: unless-stopped
    networks:
      - inception
    healthcheck:
      test: ["CMD", "curl", "-kfsSL", "https://localhost:443"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 5s

  mariadb:
    container_name: mariadb_docker
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart : unless-stopped
    healthcheck:
      test: mysqladmin ping --host=localhost -p${MYSQL_ROOT_PASSWORD}
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 5s

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      #device: /home/abravo/data/database
      device: /home/amanda/data/database
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      #device: /home/abravo/data/website
      device: /home/amanda/data/website
      o: bind

networks:
  inception:
    name: inception
    driver: bridge
