version: '3.8'

services:
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - "9000"
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443"
    restart: always
    volumes:
      - ./chemin/vers/site:/var/www/html:ro

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: motdepasse
      MYSQL_DATABASE: wordpress
      MYSQL_USER: utilisateur
      MYSQL_PASSWORD: motdepasse
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: